version: "3.9"
services:
  api:
    build: .
    container_name: antisocial-api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped